import bcrypt from 'bcrypt';
import { eq } from 'drizzle-orm';
import { db } from '../db';
import { users } from '../db/schema';

/**
 * Number of bcrypt salt rounds for password hashing.
 * Higher = more secure but slower (12 is a good balance).
 */
const SALT_ROUNDS = 12;

/**
 * Hashes a plain text password using bcrypt.
 *
 * @param password - Plain text password to hash
 * @returns Promise resolving to the hashed password string
 *
 * @example
 * ```typescript
 * const hash = await hashPassword('mypassword123');
 * // Store hash in database, never store plain passwords
 * ```
 */
export const hashPassword = async (password: string): Promise<string> => {
  return bcrypt.hash(password, SALT_ROUNDS);
};

/**
 * Verifies a plain text password against a bcrypt hash.
 *
 * @param password - Plain text password to verify
 * @param hash - Bcrypt hash from database
 * @returns Promise resolving to true if password matches, false otherwise
 *
 * @example
 * ```typescript
 * const isValid = await verifyPassword('mypassword123', user.passwordHash);
 * if (isValid) {
 *   // User authenticated
 * }
 * ```
 */
export const verifyPassword = async (
  password: string,
  hash: string
): Promise<boolean> => {
  return bcrypt.compare(password, hash);
};

/**
 * Finds a user in the database by email address.
 *
 * @param email - Email address to search for
 * @returns Promise resolving to the user object if found, null otherwise
 *
 * @example
 * ```typescript
 * const user = await findUserByEmail('user@example.com');
 * if (user) {
 *   console.log(user.id, user.email);
 * }
 * ```
 */
export const findUserByEmail = async (
  email: string
): Promise<typeof users.$inferSelect | null> => {
  const [user] = await db
    .select()
    .from(users)
    .where(eq(users.email, email))
    .limit(1);
  return user ?? null;
};

/**
 * Creates a new user in the database.
 *
 * Hashes the password before storing and returns the created user object
 * with all database fields (id, email, createdAt, etc.).
 *
 * @param email - User's email address (must be unique)
 * @param password - Plain text password (will be hashed)
 * @returns Promise resolving to the created user object
 * @throws Database error if email already exists (unique constraint)
 *
 * @example
 * ```typescript
 * const user = await createUser('user@example.com', 'securepassword123');
 * console.log(user.id); // UUID generated by database
 * ```
 */
export const createUser = async (
  email: string,
  password: string
): Promise<typeof users.$inferSelect> => {
  const passwordHash = await hashPassword(password);
  const [user] = await db
    .insert(users)
    .values({ email, passwordHash })
    .returning();

  if (!user) {
    throw new Error('Failed to create user');
  }

  return user;
};
